### ISSUE TITLE
Conclusion

### ISSUE THREAD

**Issue by DecentGradient** [josephlhall/dc25-votingvillage-report#1]
Use paper ballots

**Comment by appalliance** [comment]
Do you think the work being done by the Open Software Election Technology group will help?   Start with paper ballots but scan them to have a backup, paper ballots can be easily damaged or lost.  This was an issue in 2000 when the Hollerith cards were so over-handled, some were no longer readable.

**Comment by josephlhall** [comment]
Absolutely. There are a few efforts to apply open source here (in addition to a few very early ones including one of our own). One is the OSET effort and they are good people doing good work. LA County is building a system that we all hope will be developed and licensed under and open source framework. Finally, San Francisco has been working on open source and free software there but I'm not as familiar with it as other efforts. Holler if you want/need links.

**Comment by josephlhall** [comment]
@HuemanF it's far from that simple
